/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package trabalho;
import java.util.Map;
import java.util.HashMap;
import javax.swing.JOptionPane;

/**
 *
 * @author Matheus
 */
public class Tela_embalagens extends javax.swing.JInternalFrame {

    /**
     * Creates new form Tela_embalagens
     */
    public Tela_embalagens() 
    {
        initComponents();
       
        for ( Produtos produto : Banco_Dados.getProdutos() ) 
        {
        PRODUTO_ASSOCIADO_CB.addItem(produto.getNome());
        
        }
        for( Tipos_Embalagem embalagem: Embalagens.tipos_embalagens)
        {
            TIPO_EMBALAGEM_CB.addItem(embalagem.toString() );
        }
         
     }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        OB_TEXT_AREA = new javax.swing.JTextArea();
        ALTURA_TXT = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        BOTAO = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        TIPO_EMBALAGEM_CB = new javax.swing.JComboBox<>();
        LARGURA_TXT = new javax.swing.JTextField();
        COMPRIMENTO_TXT = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        PESO_TXT = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        PRODUTO_ASSOCIADO_CB = new javax.swing.JComboBox<>();
        jLabel12 = new javax.swing.JLabel();
        SIM_OP = new javax.swing.JCheckBox();
        NAO_OP = new javax.swing.JCheckBox();

        OB_TEXT_AREA.setColumns(20);
        OB_TEXT_AREA.setRows(5);
        jScrollPane1.setViewportView(OB_TEXT_AREA);

        jLabel6.setText("ALTURA");

        BOTAO.setText("CADASTRAR");
        BOTAO.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BOTAOActionPerformed(evt);
            }
        });

        jLabel1.setText("PRODUTO ASSOCIADO");

        jLabel7.setText("LARGURA");

        jLabel8.setText("COMPRIMENTO");

        jLabel11.setText("TIPO");

        jLabel9.setText("PESO");

        jLabel10.setText("OBSERVAÇÕES");

        jLabel12.setText("EMPILHÁVEL");

        SIM_OP.setText("SIM");
        SIM_OP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SIM_OPActionPerformed(evt);
            }
        });

        NAO_OP.setText("NAO");
        NAO_OP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NAO_OPActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(100, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(60, 60, 60))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(BOTAO)
                        .addGap(139, 139, 139))))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel9)
                            .addComponent(jLabel8)
                            .addComponent(jLabel7)
                            .addComponent(jLabel6)
                            .addComponent(jLabel1)
                            .addComponent(jLabel11)
                            .addComponent(jLabel12))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(ALTURA_TXT, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(LARGURA_TXT, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(COMPRIMENTO_TXT, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(PESO_TXT, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(TIPO_EMBALAGEM_CB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(PRODUTO_ASSOCIADO_CB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(SIM_OP)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(NAO_OP))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(28, 28, 28)
                        .addComponent(jLabel10)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(PRODUTO_ASSOCIADO_CB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(TIPO_EMBALAGEM_CB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(ALTURA_TXT, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(LARGURA_TXT, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(COMPRIMENTO_TXT, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(PESO_TXT, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel12)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(SIM_OP)
                        .addComponent(NAO_OP)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel10)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(BOTAO)
                .addContainerGap(126, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BOTAOActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BOTAOActionPerformed
        //cria um mapa(que e tipo um vetor dinamico ou um dicionario de python)
        Map<String, Produtos> mapaProdutos = new HashMap<>();
        for ( Produtos produto : Banco_Dados.getProdutos() ) 
        {
            //coloca no mapa a chave e valor
        mapaProdutos.put(produto.getNome(), produto);
        }
        //pega da combo box o nome e passa para string com casting (String)
        String nome_selecionado = (String) PRODUTO_ASSOCIADO_CB.getSelectedItem();
        //pega o valor do produto cuja chave seja o nome
        Produtos produto_selecionado = mapaProdutos.get(nome_selecionado);
        boolean empilhavel;
        if( SIM_OP.isSelected() )
        {
           empilhavel=true; 
        }
        else
        {
           empilhavel=false; 
        }
            
        boolean r=Banco_Dados.addEmbalagens(
            new Embalagens(
                produto_selecionado,
                     new Dimensoes(
                    Double.parseDouble(ALTURA_TXT.getText().trim() ),
                    Double.parseDouble(LARGURA_TXT.getText().trim() ),
                    Double.parseDouble(COMPRIMENTO_TXT.getText().trim() ) 
                     ),
                Double.parseDouble(PESO_TXT.getText().trim()),
                empilhavel, // true ou false
                OB_TEXT_AREA.getText().trim()
                ) 
        );

        if(r == true)
        {
            JOptionPane.showMessageDialog(null, "cadastrado com suceso!");
        }else
        {
            JOptionPane.showMessageDialog(null, "inválido!");
        }
    }//GEN-LAST:event_BOTAOActionPerformed

    private void SIM_OPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SIM_OPActionPerformed
        NAO_OP.setSelected(false);
    }//GEN-LAST:event_SIM_OPActionPerformed

    private void NAO_OPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NAO_OPActionPerformed
        SIM_OP.setSelected(false);
    }//GEN-LAST:event_NAO_OPActionPerformed

       

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField ALTURA_TXT;
    private javax.swing.JButton BOTAO;
    private javax.swing.JTextField COMPRIMENTO_TXT;
    private javax.swing.JTextField LARGURA_TXT;
    private javax.swing.JCheckBox NAO_OP;
    private javax.swing.JTextArea OB_TEXT_AREA;
    private javax.swing.JTextField PESO_TXT;
    private javax.swing.JComboBox<String> PRODUTO_ASSOCIADO_CB;
    private javax.swing.JCheckBox SIM_OP;
    private javax.swing.JComboBox<String> TIPO_EMBALAGEM_CB;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
