/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package trabalho;

/**
 *
 * @author Matheus
 */
public class telaInicial extends javax.swing.JFrame {

    /**
     * Creates new form telaInicial
     */
    public telaInicial() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        desktop = new javax.swing.JDesktopPane();
        barra_menu = new javax.swing.JMenuBar();
        cadastrar = new javax.swing.JMenu();
        menu_veiculos = new javax.swing.JMenuItem();
        menu_produtos = new javax.swing.JMenuItem();
        menu_embalagens = new javax.swing.JMenuItem();
        separador = new javax.swing.JPopupMenu.Separator();
        menu_sair = new javax.swing.JMenuItem();
        resumo = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout desktopLayout = new javax.swing.GroupLayout(desktop);
        desktop.setLayout(desktopLayout);
        desktopLayout.setHorizontalGroup(
            desktopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 412, Short.MAX_VALUE)
        );
        desktopLayout.setVerticalGroup(
            desktopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 289, Short.MAX_VALUE)
        );

        cadastrar.setText("Cadastro");

        menu_veiculos.setText("Veiculos");
        menu_veiculos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menu_veiculosActionPerformed(evt);
            }
        });
        cadastrar.add(menu_veiculos);

        menu_produtos.setText("Produtos");
        menu_produtos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menu_produtosActionPerformed(evt);
            }
        });
        cadastrar.add(menu_produtos);

        menu_embalagens.setText("Embalagens");
        menu_embalagens.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menu_embalagensActionPerformed(evt);
            }
        });
        cadastrar.add(menu_embalagens);
        cadastrar.add(separador);

        menu_sair.setText("Sair");
        menu_sair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menu_sairActionPerformed(evt);
            }
        });
        cadastrar.add(menu_sair);

        barra_menu.add(cadastrar);

        resumo.setText("Resumo");

        jMenuItem1.setText("resumo");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        resumo.add(jMenuItem1);

        barra_menu.add(resumo);

        setJMenuBar(barra_menu);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(desktop)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(desktop, javax.swing.GroupLayout.Alignment.TRAILING)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void menu_sairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menu_sairActionPerformed
        
        System.exit(1);
    }//GEN-LAST:event_menu_sairActionPerformed

    private void menu_veiculosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menu_veiculosActionPerformed
        Tela_veiculos tela = new Tela_veiculos();
        desktop.add(tela);
        tela.setVisible(true);
        tela.setClosable(true);
    }//GEN-LAST:event_menu_veiculosActionPerformed

    private void menu_produtosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menu_produtosActionPerformed
        Tela_produtos tela = new Tela_produtos();
        desktop.add(tela);
        tela.setVisible(true);
        tela.setClosable(true);
    }//GEN-LAST:event_menu_produtosActionPerformed

    private void menu_embalagensActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menu_embalagensActionPerformed
        Tela_embalagens tela = new Tela_embalagens();
        desktop.add(tela);
        tela.setVisible(true);
        tela.setClosable(true);
    }//GEN-LAST:event_menu_embalagensActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        tela_resumo tela = new tela_resumo();
        desktop.add(tela);
        tela.setVisible(true);
        tela.setClosable(true);
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(telaInicial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(telaInicial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(telaInicial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(telaInicial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new telaInicial().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuBar barra_menu;
    private javax.swing.JMenu cadastrar;
    private javax.swing.JDesktopPane desktop;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem menu_embalagens;
    private javax.swing.JMenuItem menu_produtos;
    private javax.swing.JMenuItem menu_sair;
    private javax.swing.JMenuItem menu_veiculos;
    private javax.swing.JMenu resumo;
    private javax.swing.JPopupMenu.Separator separador;
    // End of variables declaration//GEN-END:variables
}
