/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package trabalho;

import java.util.HashMap;
import java.util.HashSet;
import java.util.Map;
import java.util.Set;
import javax.swing.JOptionPane;
/**
 *
 * @author Matheus
 */
public class tela_resumo extends javax.swing.JInternalFrame {

    /**
     * Creates new form tela_resumo
     */
    public tela_resumo() 
    {
        initComponents();
        gerarResumo();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        resumoArea = new javax.swing.JTextArea();
        jButton1 = new javax.swing.JButton();

        resumoArea.setColumns(20);
        resumoArea.setRows(5);
        jScrollPane1.setViewportView(resumoArea);

        jButton1.setText("atualizar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(27, 27, 27)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 340, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(155, 155, 155)
                        .addComponent(jButton1)))
                .addContainerGap(27, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 194, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 11, Short.MAX_VALUE)
                .addComponent(jButton1)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        gerarResumo();
    }//GEN-LAST:event_jButton1ActionPerformed

 private void gerarResumo() 
 {
     
        StringBuilder resumo = new StringBuilder();
        int aberto = 0, bau = 0, pickup = 0, carreta = 0, urbano = 0;
        //for each por todos os veiculos cadastrados
        
        for (Veiculos v : Banco_Dados.getVeiculos() ) 
        {
            //faz a comparacao pra saber qual o tipo de veiculo
            
            String nome = v.getTipo();
            if (nome.contains("ABERTO")) aberto++;
            else if (nome.contains("BAU")) bau++;
            else if (nome.contains("PICKUP")) pickup++;
            else if (nome.contains("CARRETA")) carreta++;
            else if (nome.contains("URBANO")) urbano++;
        }
        //soma total
        int totalVeiculos = aberto + bau + pickup + carreta + urbano;
        //adiciona no STRG builder
        resumo.append("Número de veículos por tipo:\n");
        resumo.append("- Caminhão Aberto: ").append(aberto).append("\n");
        resumo.append("- Caminhão Baú: ").append(bau).append("\n");
        resumo.append("- Pickup: ").append(pickup).append("\n");
        resumo.append("- Carreta: ").append(carreta).append("\n");
        resumo.append("- Veículo Urbano de Carga: ").append(urbano).append("\n");
        resumo.append("Total de veículos: ").append(totalVeiculos).append("\n\n");

        // --- Produtos ---
        //criei um vetor associativo em que o da direita é a chave e o da esquerda o valor
        //poderia ser hashmap<> map=new hashmap<>();
        //deixa mais generico,visto que map é uma interface, e nao uma classe propriamente dita, como List e ArrayList, em que lis é a interface a a outra sua implementacao
        Map<String, Integer> produtosPorTipo = new HashMap<>();
        //cria uma lista que nao permite itens repetidos
        //interface e implementacao dela
        Set<String> familias = new HashSet<>();
        Set<String> tipos = new HashSet<>();
        Set<String> lotes = new HashSet<>();
        //for each para passando por todos os produtos cadastrados
        for (Produtos p : Banco_Dados.getProdutos() ) 
        {
 /*
coloca no hashmap a chave(tipo do produto) e a quantidade    //ger or default serve para ele calcular se a chave já apareceu nesse hashmap 
e o +1 é pra ele adicionar toda vez que encontra uma chave,se é a primeira vez que ela aparece,ele comeca com o 0 e incrementa +1
*/
            
            produtosPorTipo.put(p.getTipo(), produtosPorTipo.getOrDefault(p.getTipo(), 0) + 1);
            familias.add(p.getFamília());
            tipos.add(p.getTipo());
            lotes.add(p.getLote());
        }

        resumo.append("Número de produtos por tipo:\n");
        int totalProdutos = 0;
        //key set pega todas as chaves de um map e as devolve num set(lista que nao tem duplicatas)
        for (String tipo : produtosPorTipo.keySet() ) 
        {
            resumo.append("- ").append(tipo).append(": ").append(produtosPorTipo.get(tipo)).append("\n");
            //get num hashmap é pra pegar a chave
            totalProdutos += produtosPorTipo.get(tipo);
        }
        resumo.append("Total de produtos: ").append(totalProdutos).append("\n\n");

        int totalEmbalagens = Banco_Dados.getEmbalagens().size();

        resumo.append("Número de embalagens por tipo:\n");
        resumo.append("- Caixa: ").append(totalEmbalagens).append("\n");
        resumo.append("- Tambor: 0\n");
        resumo.append("- Saco: 0\n");
        resumo.append("- Palete: 0\n");
        resumo.append("Total de embalagens: ").append(totalEmbalagens).append("\n\n");

        // --- Outras informações ---
        resumo.append("Número de famílias de produtos: ").append(familias.size()).append("\n");
        resumo.append("Número de tipos de produtos: ").append(tipos.size()).append("\n");
        resumo.append("Número de lotes cadastrados: ").append(lotes.size()).append("\n");

        //bota todo o strg builder na text area
        resumoArea.setText(resumo.toString());
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea resumoArea;
    // End of variables declaration//GEN-END:variables
}
